name: Build

on:
  push:
    branches:
      - master
      - development
      - alpha
      - beta
      - next
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - development
      - alpha
      - beta
      - next

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build the project
      run: msbuild /t:Build /p:Configuration=Release /p:Platform="x64"
